# Log to stdout without timestamps
[Log]
Path = "-"
Timestamps = false

# Write check results to disk
[Database]
Module = "persistent"

[Database.Config]
Path = "/var/lib/gesundheit/data"

# Enable if you need a pretty web interface
[Http]
Enabled = false
Listen = "127.0.0.1:8080"

# Load modules config from modules.d
[Modules]
Config = "modules.d/*.toml"
